# Generated by Django 5.1.5 on 2025-02-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_has_variants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_variants',
            new_name='has_condition',
        ),
    ]
